[package]
name = "shunya-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13"
shunya-proto = { version = "0.1.0", path = "../shunya-proto" }
slint = "1.18.1"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.12"

[build-dependencies]
slint-build = "1.18.1"
