// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: shunya/v1/shunya.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{0}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{1}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type Device struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Class            string                 `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Model            string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Serial           string                 `protobuf:"bytes,4,opt,name=serial,proto3" json:"serial,omitempty"`
	Firmware         string                 `protobuf:"bytes,5,opt,name=firmware,proto3" json:"firmware,omitempty"`
	CapacityBytes    uint64                 `protobuf:"varint,6,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	SupportedMethods []string               `protobuf:"bytes,7,rep,name=supported_methods,json=supportedMethods,proto3" json:"supported_methods,omitempty"`
	IsSystemDisk     bool                   `protobuf:"varint,8,opt,name=is_system_disk,json=isSystemDisk,proto3" json:"is_system_disk,omitempty"`
	IsBootMedium     bool                   `protobuf:"varint,9,opt,name=is_boot_medium,json=isBootMedium,proto3" json:"is_boot_medium,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{2}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Device) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Device) GetFirmware() string {
	if x != nil {
		return x.Firmware
	}
	return ""
}

func (x *Device) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *Device) GetSupportedMethods() []string {
	if x != nil {
		return x.SupportedMethods
	}
	return nil
}

func (x *Device) GetIsSystemDisk() bool {
	if x != nil {
		return x.IsSystemDisk
	}
	return false
}

func (x *Device) GetIsBootMedium() bool {
	if x != nil {
		return x.IsBootMedium
	}
	return false
}

type GetChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRequest) Reset() {
	*x = GetChallengeRequest{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRequest) ProtoMessage() {}

func (x *GetChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRequest) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{3}
}

func (x *GetChallengeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetChallengeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChallengeString string                 `protobuf:"bytes,1,opt,name=challenge_string,json=challengeString,proto3" json:"challenge_string,omitempty"` // e.g., "WIPE-9421"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetChallengeResponse) Reset() {
	*x = GetChallengeResponse{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeResponse) ProtoMessage() {}

func (x *GetChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeResponse) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{4}
}

func (x *GetChallengeResponse) GetChallengeString() string {
	if x != nil {
		return x.ChallengeString
	}
	return ""
}

type StartJobRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DeviceId          string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ChallengeResponse string                 `protobuf:"bytes,2,opt,name=challenge_response,json=challengeResponse,proto3" json:"challenge_response,omitempty"` // User must provide the exact challenge_string
	RequestedMethod   string                 `protobuf:"bytes,3,opt,name=requested_method,json=requestedMethod,proto3" json:"requested_method,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{5}
}

func (x *StartJobRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *StartJobRequest) GetChallengeResponse() string {
	if x != nil {
		return x.ChallengeResponse
	}
	return ""
}

func (x *StartJobRequest) GetRequestedMethod() string {
	if x != nil {
		return x.RequestedMethod
	}
	return ""
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{6}
}

func (x *StartJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{7}
}

func (x *StreamEventsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	StepName        string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	ProgressPercent float32                `protobuf:"fixed32,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobEvent) Reset() {
	*x = JobEvent{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobEvent) ProtoMessage() {}

func (x *JobEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobEvent.ProtoReflect.Descriptor instead.
func (*JobEvent) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{8}
}

func (x *JobEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobEvent) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *JobEvent) GetProgressPercent() float32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *JobEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRecoveryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceDeviceId  string                 `protobuf:"bytes,1,opt,name=source_device_id,json=sourceDeviceId,proto3" json:"source_device_id,omitempty"`
	OutputDirectory string                 `protobuf:"bytes,2,opt,name=output_directory,json=outputDirectory,proto3" json:"output_directory,omitempty"`
	Profile         string                 `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartRecoveryRequest) Reset() {
	*x = StartRecoveryRequest{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecoveryRequest) ProtoMessage() {}

func (x *StartRecoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecoveryRequest.ProtoReflect.Descriptor instead.
func (*StartRecoveryRequest) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{9}
}

func (x *StartRecoveryRequest) GetSourceDeviceId() string {
	if x != nil {
		return x.SourceDeviceId
	}
	return ""
}

func (x *StartRecoveryRequest) GetOutputDirectory() string {
	if x != nil {
		return x.OutputDirectory
	}
	return ""
}

func (x *StartRecoveryRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type StartRecoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecoveryResponse) Reset() {
	*x = StartRecoveryResponse{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecoveryResponse) ProtoMessage() {}

func (x *StartRecoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecoveryResponse.ProtoReflect.Descriptor instead.
func (*StartRecoveryResponse) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{10}
}

func (x *StartRecoveryResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{11}
}

func (x *GetCertificateRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertJson      string                 `protobuf:"bytes,1,opt,name=cert_json,json=certJson,proto3" json:"cert_json,omitempty"`
	PdfData       []byte                 `protobuf:"bytes,2,opt,name=pdf_data,json=pdfData,proto3" json:"pdf_data,omitempty"`
	QrPayload     string                 `protobuf:"bytes,3,opt,name=qr_payload,json=qrPayload,proto3" json:"qr_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	mi := &file_shunya_v1_shunya_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shunya_v1_shunya_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_shunya_v1_shunya_proto_rawDescGZIP(), []int{12}
}

func (x *GetCertificateResponse) GetCertJson() string {
	if x != nil {
		return x.CertJson
	}
	return ""
}

func (x *GetCertificateResponse) GetPdfData() []byte {
	if x != nil {
		return x.PdfData
	}
	return nil
}

func (x *GetCertificateResponse) GetQrPayload() string {
	if x != nil {
		return x.QrPayload
	}
	return ""
}

var File_shunya_v1_shunya_proto protoreflect.FileDescriptor

const file_shunya_v1_shunya_proto_rawDesc = "" +
	"\n" +
	"\x16shunya/v1/shunya.proto\x12\tshunya.v1\"\x14\n" +
	"\x12ListDevicesRequest\"B\n" +
	"\x13ListDevicesResponse\x12+\n" +
	"\adevices\x18\x01 \x03(\v2\x11.shunya.v1.DeviceR\adevices\"\x98\x02\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05class\x18\x02 \x01(\tR\x05class\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x04 \x01(\tR\x06serial\x12\x1a\n" +
	"\bfirmware\x18\x05 \x01(\tR\bfirmware\x12%\n" +
	"\x0ecapacity_bytes\x18\x06 \x01(\x04R\rcapacityBytes\x12+\n" +
	"\x11supported_methods\x18\a \x03(\tR\x10supportedMethods\x12$\n" +
	"\x0eis_system_disk\x18\b \x01(\bR\fisSystemDisk\x12$\n" +
	"\x0eis_boot_medium\x18\t \x01(\bR\fisBootMedium\"2\n" +
	"\x13GetChallengeRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"A\n" +
	"\x14GetChallengeResponse\x12)\n" +
	"\x10challenge_string\x18\x01 \x01(\tR\x0fchallengeString\"\x88\x01\n" +
	"\x0fStartJobRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12-\n" +
	"\x12challenge_response\x18\x02 \x01(\tR\x11challengeResponse\x12)\n" +
	"\x10requested_method\x18\x03 \x01(\tR\x0frequestedMethod\")\n" +
	"\x10StartJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x13StreamEventsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9b\x01\n" +
	"\bJobEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x02R\x0fprogressPercent\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x85\x01\n" +
	"\x14StartRecoveryRequest\x12(\n" +
	"\x10source_device_id\x18\x01 \x01(\tR\x0esourceDeviceId\x12)\n" +
	"\x10output_directory\x18\x02 \x01(\tR\x0foutputDirectory\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\".\n" +
	"\x15StartRecoveryResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\".\n" +
	"\x15GetCertificateRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"o\n" +
	"\x16GetCertificateResponse\x12\x1b\n" +
	"\tcert_json\x18\x01 \x01(\tR\bcertJson\x12\x19\n" +
	"\bpdf_data\x18\x02 \x01(\fR\apdfData\x12\x1d\n" +
	"\n" +
	"qr_payload\x18\x03 \x01(\tR\tqrPayload2]\n" +
	"\rDeviceService\x12L\n" +
	"\vListDevices\x12\x1d.shunya.v1.ListDevicesRequest\x1a\x1e.shunya.v1.ListDevicesResponse2\xe9\x01\n" +
	"\n" +
	"JobService\x12O\n" +
	"\fGetChallenge\x12\x1e.shunya.v1.GetChallengeRequest\x1a\x1f.shunya.v1.GetChallengeResponse\x12C\n" +
	"\bStartJob\x12\x1a.shunya.v1.StartJobRequest\x1a\x1b.shunya.v1.StartJobResponse\x12E\n" +
	"\fStreamEvents\x12\x1e.shunya.v1.StreamEventsRequest\x1a\x13.shunya.v1.JobEvent0\x012e\n" +
	"\x0fRecoveryService\x12R\n" +
	"\rStartRecovery\x12\x1f.shunya.v1.StartRecoveryRequest\x1a .shunya.v1.StartRecoveryResponse2k\n" +
	"\x12CertificateService\x12U\n" +
	"\x0eGetCertificate\x12 .shunya.v1.GetCertificateRequest\x1a!.shunya.v1.GetCertificateResponseB\x18Z\x16shunya/proto/shunya/v1b\x06proto3"

var (
	file_shunya_v1_shunya_proto_rawDescOnce sync.Once
	file_shunya_v1_shunya_proto_rawDescData []byte
)

func file_shunya_v1_shunya_proto_rawDescGZIP() []byte {
	file_shunya_v1_shunya_proto_rawDescOnce.Do(func() {
		file_shunya_v1_shunya_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shunya_v1_shunya_proto_rawDesc), len(file_shunya_v1_shunya_proto_rawDesc)))
	})
	return file_shunya_v1_shunya_proto_rawDescData
}

var file_shunya_v1_shunya_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_shunya_v1_shunya_proto_goTypes = []any{
	(*ListDevicesRequest)(nil),     // 0: shunya.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),    // 1: shunya.v1.ListDevicesResponse
	(*Device)(nil),                 // 2: shunya.v1.Device
	(*GetChallengeRequest)(nil),    // 3: shunya.v1.GetChallengeRequest
	(*GetChallengeResponse)(nil),   // 4: shunya.v1.GetChallengeResponse
	(*StartJobRequest)(nil),        // 5: shunya.v1.StartJobRequest
	(*StartJobResponse)(nil),       // 6: shunya.v1.StartJobResponse
	(*StreamEventsRequest)(nil),    // 7: shunya.v1.StreamEventsRequest
	(*JobEvent)(nil),               // 8: shunya.v1.JobEvent
	(*StartRecoveryRequest)(nil),   // 9: shunya.v1.StartRecoveryRequest
	(*StartRecoveryResponse)(nil),  // 10: shunya.v1.StartRecoveryResponse
	(*GetCertificateRequest)(nil),  // 11: shunya.v1.GetCertificateRequest
	(*GetCertificateResponse)(nil), // 12: shunya.v1.GetCertificateResponse
}
var file_shunya_v1_shunya_proto_depIdxs = []int32{
	2,  // 0: shunya.v1.ListDevicesResponse.devices:type_name -> shunya.v1.Device
	0,  // 1: shunya.v1.DeviceService.ListDevices:input_type -> shunya.v1.ListDevicesRequest
	3,  // 2: shunya.v1.JobService.GetChallenge:input_type -> shunya.v1.GetChallengeRequest
	5,  // 3: shunya.v1.JobService.StartJob:input_type -> shunya.v1.StartJobRequest
	7,  // 4: shunya.v1.JobService.StreamEvents:input_type -> shunya.v1.StreamEventsRequest
	9,  // 5: shunya.v1.RecoveryService.StartRecovery:input_type -> shunya.v1.StartRecoveryRequest
	11, // 6: shunya.v1.CertificateService.GetCertificate:input_type -> shunya.v1.GetCertificateRequest
	1,  // 7: shunya.v1.DeviceService.ListDevices:output_type -> shunya.v1.ListDevicesResponse
	4,  // 8: shunya.v1.JobService.GetChallenge:output_type -> shunya.v1.GetChallengeResponse
	6,  // 9: shunya.v1.JobService.StartJob:output_type -> shunya.v1.StartJobResponse
	8,  // 10: shunya.v1.JobService.StreamEvents:output_type -> shunya.v1.JobEvent
	10, // 11: shunya.v1.RecoveryService.StartRecovery:output_type -> shunya.v1.StartRecoveryResponse
	12, // 12: shunya.v1.CertificateService.GetCertificate:output_type -> shunya.v1.GetCertificateResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_shunya_v1_shunya_proto_init() }
func file_shunya_v1_shunya_proto_init() {
	if File_shunya_v1_shunya_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shunya_v1_shunya_proto_rawDesc), len(file_shunya_v1_shunya_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_shunya_v1_shunya_proto_goTypes,
		DependencyIndexes: file_shunya_v1_shunya_proto_depIdxs,
		MessageInfos:      file_shunya_v1_shunya_proto_msgTypes,
	}.Build()
	File_shunya_v1_shunya_proto = out.File
	file_shunya_v1_shunya_proto_goTypes = nil
	file_shunya_v1_shunya_proto_depIdxs = nil
}
