[package]
name = "shunya-device"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.21"

[target.'cfg(target_os = "linux")'.dependencies]
rustix = { version = "0.38", features = ["fs"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_Ioctl",
    "Win32_Devices_DeviceAndDriverInstallation"
] }

[target.'cfg(target_os = "macos")'.dependencies]
io-kit-sys = "0.4.1"
core-foundation = "0.9.4"
