name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        working-directory: crates
        run: cargo build --release

      - name: Test
        working-directory: crates
        run: cargo test --release

      - name: Clippy
        working-directory: crates
        run: cargo clippy -- -D warnings
